name: Run Fraud Detection Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib seaborn plotly scikit-learn catboost lightgbm xgboost jupyter nbconvert

    - name: Run data preprocessing script
      run: |
        python data_preprocessing.py

    - name: Run data analysis script
      run: |
        python data_analysis.py

    - name: Run model training script
      run: |
        python model_training.py
